export const DEPARTMENT_CODES: Record<string, string> = {
  'Amazonas': 'AMA',
  'Antioquia': 'ANT',
  'Arauca': 'ARA',
  'Atlántico': 'ATL',
  'Bolívar': 'BOL',
  'Boyacá': 'BOY',
  'Caldas': 'CAL',
  'Caquetá': 'CAQ',
  'Casanare': 'CAS',
  'Cauca': 'CAU',
  'Cesar': 'CES',
  'Chocó': 'CHO',
  'Córdoba': 'COR',
  'Cundinamarca': 'CUN',
  'Guainía': 'GUA',
  'Guaviare': 'GUV',
  'Huila': 'HUI',
  'La Guajira': 'LAG',
  'Magdalena': 'MAG',
  'Meta': 'MET',
  'Nariño': 'NAR',
  'Norte de Santander': 'NSA',
  'Putumayo': 'PUT',
  'Quindío': 'QUI',
  'Risaralda': 'RIS',
  'San Andrés y Providencia': 'SAP',
  'Santander': 'SAN',
  'Sucre': 'SUC',
  'Tolima': 'TOL',
  'Valle del Cauca': 'VAC',
  'Vaupés': 'VAU',
  'Vichada': 'VID',
  'Bogotá': 'DC',
  'Bogotá D.C.': 'DC',
};

export function toDepartmentCode(departmentName: string): string {
  return DEPARTMENT_CODES[departmentName] ?? departmentName.slice(0, 3).toUpperCase();
}
